/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etudiant;

/**
 *
 * @author Soxna Maguette
 */
public class AcceuilPersonnel extends javax.swing.JFrame {

    /**
     * Creates new form AcceuilPersonnel
     */
    public AcceuilPersonnel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        MenuEtudiant = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        GestionDesDiplomes = new java.awt.Panel();
        label1 = new java.awt.Label();
        textField24 = new java.awt.TextField();
        button1 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        VerificationDiplome = new java.awt.Panel();
        label2 = new java.awt.Label();
        textField25 = new java.awt.TextField();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 500));
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(248, 248, 243));
        panel1.setMinimumSize(new java.awt.Dimension(950, 500));
        panel1.setLayout(null);

        MenuEtudiant.setBackground(new java.awt.Color(102, 204, 255));
        MenuEtudiant.setVisible(false);
        MenuEtudiant.setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Deconnexion");
        MenuEtudiant.add(jButton1);
        jButton1.setBounds(760, 0, 150, 30);

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Gestion Diplomes");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MenuEtudiant.add(jButton2);
        jButton2.setBounds(40, 0, 150, 30);

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Verification Diplome");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        MenuEtudiant.add(jButton3);
        jButton3.setBounds(220, 0, 180, 30);

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Exploitation Des Donnees");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuEtudiant.add(jButton4);
        jButton4.setBounds(440, 0, 210, 30);

        panel1.add(MenuEtudiant);
        MenuEtudiant.setBounds(0, 0, 940, 30);

        GestionDesDiplomes.setBackground(new java.awt.Color(248, 248, 243));
        GestionDesDiplomes.setVisible(false);
        GestionDesDiplomes.setLayout(null);

        label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 204, 255));
        label1.setText("Pour afficher plus d'infos sur vos amis (es), veuillez saisir son code permenant");
        GestionDesDiplomes.add(label1);
        label1.setBounds(400, 10, 530, 30);

        textField24.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField24ActionPerformed(evt);
            }
        });
        GestionDesDiplomes.add(textField24);
        textField24.setBounds(540, 50, 220, 40);

        button1.setBackground(new java.awt.Color(102, 204, 255));
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Rechercher");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        GestionDesDiplomes.add(button1);
        button1.setBounds(770, 50, 120, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code Permenant", "Prenom", "Nom", "Email", "Telephone", "Domicile"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        GestionDesDiplomes.add(jScrollPane2);
        jScrollPane2.setBounds(20, 130, 640, 280);

        panel1.add(GestionDesDiplomes);
        GestionDesDiplomes.setBounds(0, 40, 960, 470);

        VerificationDiplome.setBackground(new java.awt.Color(248, 248, 243));
        VerificationDiplome.setVisible(false);
        VerificationDiplome.setLayout(null);

        label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(102, 204, 255));
        label2.setText("Veuillez saisir le code permenant de l'etudiant");
        VerificationDiplome.add(label2);
        label2.setBounds(540, 0, 330, 30);

        textField25.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField25ActionPerformed(evt);
            }
        });
        VerificationDiplome.add(textField25);
        textField25.setBounds(540, 50, 220, 40);

        button2.setBackground(new java.awt.Color(102, 204, 255));
        button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("Rechercher");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        VerificationDiplome.add(button2);
        button2.setBounds(770, 50, 120, 40);

        panel1.add(VerificationDiplome);
        VerificationDiplome.setBounds(0, 40, 960, 470);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 960, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField24ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void textField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField25ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilPersonnel().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel GestionDesDiplomes;
    private java.awt.Panel MenuEtudiant;
    private java.awt.Panel VerificationDiplome;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Panel panel1;
    private java.awt.TextField textField24;
    private java.awt.TextField textField25;
    // End of variables declaration//GEN-END:variables
}
