/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etudiant;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;

/**
 *
 * @author Soxna Maguette
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        lienRegister = new java.awt.Label();
        button1 = new java.awt.Button();
        label4 = new java.awt.Label();
        jComboBox1 = new javax.swing.JComboBox<>();
        label3 = new java.awt.Label();
        errorLabel = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 248, 243));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        label1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 204, 255));
        label1.setText("Nom d'utilisateur :");
        jPanel1.add(label1);
        label1.setBounds(240, 10, 320, 40);

        textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        jPanel1.add(textField1);
        textField1.setBounds(240, 50, 340, 50);

        jPasswordField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(240, 150, 340, 50);

        lienRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lienRegister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lienRegister.setForeground(new java.awt.Color(102, 204, 255));
        lienRegister.setText("S'inscrire si vous etes nouveau");
        lienRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lienRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(lienRegister);
        lienRegister.setBounds(240, 370, 360, 41);

        button1.setBackground(new java.awt.Color(102, 204, 255));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Se connecter");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);
        button1.setBounds(240, 310, 340, 50);

        label4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label4.setForeground(new java.awt.Color(102, 204, 255));
        label4.setText("Mot de pass :");
        jPanel1.add(label4);
        label4.setBounds(240, 110, 330, 30);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "etudiant", "personnel", "admin" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setName(""); // NOI18N
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(240, 250, 340, 50);

        label3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label3.setForeground(new java.awt.Color(102, 204, 255));
        label3.setText("Type d'utilisateur :");
        jPanel1.add(label3);
        label3.setBounds(240, 200, 320, 40);

        errorLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(errorLabel);
        errorLabel.setBounds(240, 420, 410, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, 0, 870, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void lienRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienRegisterMouseClicked
        // TODO add your handling code here:

        AcceuilEtudiant loginPage = new AcceuilEtudiant();
        loginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lienRegisterMouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:

        authenticateEtudiants() ;

    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label errorLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label lienRegister;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables


//POUR ETUDIANTS
  private void authenticateEtudiants() {
    int username = Integer.parseInt(textField1.getText());
    String password = new String(jPasswordField1.getPassword());
    String typeUtilisateur = (String) jComboBox1.getSelectedItem();
    
     if (username==0 || password.isEmpty() ) {
            setErrorLabel("Veuillez remplir tous les champs.");}
           
        else{
         Connection    connection = (Connection) connecterDB.connecterDB();
        if (connection != null) {
            try {
                String queryConnexion = "SELECT * FROM utilisateurs WHERE id   = ? AND motDePasse = ? AND type_utilisateur = ?  ";
                try (PreparedStatement preparedStatement = (PreparedStatement) connection.prepareStatement(queryConnexion)) {
                    preparedStatement.setInt(1, username);
                    preparedStatement.setString(2, password); 
                    preparedStatement.setString(3, typeUtilisateur); 
                    java.sql.ResultSet resultSet = preparedStatement.executeQuery();

                    if (resultSet.next()) {
                        
                          // Ouvrir la fenêtre Infos
                            AcceuilEtudiant infos = new AcceuilEtudiant();
                            infos.setVisible(true);
    
                             // Fermer la fenêtre courante  
                            this.dispose(); 
                    } else {
                        setErrorLabel("Nom d'utilisateur ou mot de passe incorrect.");
                    }
                }
            } catch (Exception ex) {
                
                
                setErrorLabel("Erreur lors de la connexion");
               
            } finally {
                connecterDB.fermerConnexion(connection);
            }
        }
        
        }
        
       
        
    }
  
  
   private void setErrorLabel(String message) {
        errorLabel.setText("Erreur : " + message);
    }
 
}



