/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etudiant;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Soxna Maguette
 */
public class NewEtudiant extends javax.swing.JFrame {

    
      private PreparedStatement preparedStatementEtudiant, preparedStatementPromotion, preparedStatementParcours, preparedStatementCursus;
  
      
      
    public NewEtudiant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModifierCursusUniversite = new java.awt.Panel();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        anneDebut = new java.awt.TextField();
        anneeFin = new java.awt.TextField();
        buttonCursus = new java.awt.Button();
        errorLabel = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        ModifierInfosEtudiant = new java.awt.Panel();
        label7 = new java.awt.Label();
        mail = new java.awt.TextField();
        buttoninfos = new java.awt.Button();
        label8 = new java.awt.Label();
        textField8 = new java.awt.TextField();
        label9 = new java.awt.Label();
        codePermenant = new java.awt.TextField();
        label10 = new java.awt.Label();
        tel = new java.awt.TextField();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        prenom = new java.awt.TextField();
        naissance = new java.awt.TextField();
        label22 = new java.awt.Label();
        nom = new java.awt.TextField();
        errorLabel1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        ModifierParcoursPro = new java.awt.Panel();
        label15 = new java.awt.Label();
        anneFinPro = new java.awt.TextField();
        contrat = new java.awt.TextField();
        entreprise = new java.awt.TextField();
        posteOccupe = new java.awt.TextField();
        anneeDebutPro = new java.awt.TextField();
        buttonparcoursPro = new java.awt.Button();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        errorLabel2 = new java.awt.Label();
        ModifierInscriptionMaster = new java.awt.Panel();
        label20 = new java.awt.Label();
        nouveauMaster = new java.awt.TextField();
        universite = new java.awt.TextField();
        label21 = new java.awt.Label();
        boutonInscription = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        ModifierCursusUniversite.setBackground(new java.awt.Color(248, 248, 243));
        ModifierCursusUniversite.setMinimumSize(new java.awt.Dimension(800, 500));
        ModifierCursusUniversite.setName(""); // NOI18N
        ModifierCursusUniversite.setPreferredSize(new java.awt.Dimension(800, 500));
        ModifierCursusUniversite.setVisible(false);
        ModifierCursusUniversite.setLayout(null);

        label13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label13.setForeground(new java.awt.Color(102, 204, 255));
        label13.setText("Annee De Debut :");
        ModifierCursusUniversite.add(label13);
        label13.setBounds(60, 110, 210, 30);

        label14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label14.setForeground(new java.awt.Color(102, 204, 255));
        label14.setText("Anne De Fin :");
        ModifierCursusUniversite.add(label14);
        label14.setBounds(500, 110, 210, 30);

        anneDebut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierCursusUniversite.add(anneDebut);
        anneDebut.setBounds(60, 150, 230, 50);

        anneeFin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierCursusUniversite.add(anneeFin);
        anneeFin.setBounds(500, 150, 230, 50);

        buttonCursus.setBackground(new java.awt.Color(102, 204, 255));
        buttonCursus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCursus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttonCursus.setForeground(new java.awt.Color(255, 255, 255));
        buttonCursus.setLabel("Enregistrer");
        buttonCursus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCursusActionPerformed(evt);
            }
        });
        ModifierCursusUniversite.add(buttonCursus);
        buttonCursus.setBounds(240, 270, 270, 50);

        errorLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        ModifierCursusUniversite.add(errorLabel);
        errorLabel.setBounds(230, 360, 340, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Veuilllez nous erenseigner votre");
        ModifierCursusUniversite.add(jLabel1);
        jLabel1.setBounds(140, 20, 610, 50);

        getContentPane().add(ModifierCursusUniversite);
        ModifierCursusUniversite.setBounds(0, 0, 810, 510);

        ModifierInfosEtudiant.setBackground(new java.awt.Color(248, 248, 243));
        ModifierInfosEtudiant.setMinimumSize(new java.awt.Dimension(800, 560));
        ModifierInfosEtudiant.setLayout(null);

        label7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(102, 204, 255));
        label7.setText("Email  :");
        ModifierInfosEtudiant.add(label7);
        label7.setBounds(480, 160, 230, 25);

        mail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierInfosEtudiant.add(mail);
        mail.setBounds(480, 200, 210, 40);

        buttoninfos.setBackground(new java.awt.Color(102, 204, 255));
        buttoninfos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttoninfos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttoninfos.setForeground(new java.awt.Color(255, 255, 255));
        buttoninfos.setLabel("Enregistrer");
        buttoninfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoninfosActionPerformed(evt);
            }
        });
        ModifierInfosEtudiant.add(buttoninfos);
        buttoninfos.setBounds(480, 390, 210, 40);

        label8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(102, 204, 255));
        label8.setText("Domicile  :");
        ModifierInfosEtudiant.add(label8);
        label8.setBounds(480, 250, 230, 25);

        textField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField8ActionPerformed(evt);
            }
        });
        ModifierInfosEtudiant.add(textField8);
        textField8.setBounds(480, 290, 210, 40);

        label9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(102, 204, 255));
        label9.setText("Code Permenant  :");
        ModifierInfosEtudiant.add(label9);
        label9.setBounds(100, 55, 230, 20);

        codePermenant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierInfosEtudiant.add(codePermenant);
        codePermenant.setBounds(100, 90, 210, 40);

        label10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(102, 204, 255));
        label10.setText("Telephone  :");
        ModifierInfosEtudiant.add(label10);
        label10.setBounds(480, 50, 230, 25);

        tel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierInfosEtudiant.add(tel);
        tel.setBounds(480, 90, 210, 40);

        label11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label11.setForeground(new java.awt.Color(102, 204, 255));
        label11.setText("Prenom  :");
        ModifierInfosEtudiant.add(label11);
        label11.setBounds(100, 160, 230, 25);

        label12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label12.setForeground(new java.awt.Color(102, 204, 255));
        label12.setText("Date De Naissance  :");
        ModifierInfosEtudiant.add(label12);
        label12.setBounds(100, 350, 230, 25);

        prenom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierInfosEtudiant.add(prenom);
        prenom.setBounds(100, 200, 210, 40);

        naissance.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierInfosEtudiant.add(naissance);
        naissance.setBounds(100, 390, 210, 40);

        label22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label22.setForeground(new java.awt.Color(102, 204, 255));
        label22.setText("Nom  :");
        ModifierInfosEtudiant.add(label22);
        label22.setBounds(100, 250, 230, 25);

        nom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierInfosEtudiant.add(nom);
        nom.setBounds(100, 290, 210, 40);

        errorLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorLabel1.setForeground(new java.awt.Color(255, 51, 51));
        ModifierInfosEtudiant.add(errorLabel1);
        errorLabel1.setBounds(230, 430, 340, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setText("Veuillez  nous renseigner sur vos infos personnel");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        ModifierInfosEtudiant.add(jLabel2);
        jLabel2.setBounds(110, 0, 630, 40);

        getContentPane().add(ModifierInfosEtudiant);
        ModifierInfosEtudiant.setBounds(0, 0, 810, 500);

        ModifierParcoursPro.setBackground(new java.awt.Color(248, 248, 243));
        ModifierParcoursPro.setMinimumSize(new java.awt.Dimension(800, 500));
        ModifierParcoursPro.setVisible(false);
        ModifierParcoursPro.setLayout(null);

        label15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label15.setForeground(new java.awt.Color(102, 204, 255));
        label15.setText("Entreprise :");
        ModifierParcoursPro.add(label15);
        label15.setBounds(480, 130, 210, 30);

        anneFinPro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierParcoursPro.add(anneFinPro);
        anneFinPro.setBounds(40, 180, 220, 40);

        contrat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierParcoursPro.add(contrat);
        contrat.setBounds(480, 70, 220, 40);

        entreprise.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierParcoursPro.add(entreprise);
        entreprise.setBounds(480, 170, 220, 40);

        posteOccupe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierParcoursPro.add(posteOccupe);
        posteOccupe.setBounds(40, 290, 220, 40);

        anneeDebutPro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierParcoursPro.add(anneeDebutPro);
        anneeDebutPro.setBounds(40, 80, 220, 40);

        buttonparcoursPro.setBackground(new java.awt.Color(102, 204, 255));
        buttonparcoursPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonparcoursPro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttonparcoursPro.setForeground(new java.awt.Color(255, 255, 255));
        buttonparcoursPro.setLabel("Ajouter");
        buttonparcoursPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonparcoursProActionPerformed(evt);
            }
        });
        ModifierParcoursPro.add(buttonparcoursPro);
        buttonparcoursPro.setBounds(480, 280, 230, 40);

        label16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label16.setForeground(new java.awt.Color(102, 204, 255));
        label16.setText("Annee De Debut :");
        ModifierParcoursPro.add(label16);
        label16.setBounds(40, 40, 210, 30);

        label17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label17.setForeground(new java.awt.Color(102, 204, 255));
        label17.setText("Annee De Fin :");
        ModifierParcoursPro.add(label17);
        label17.setBounds(40, 140, 210, 30);

        label18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label18.setForeground(new java.awt.Color(102, 204, 255));
        label18.setText("Poste Occupe");
        ModifierParcoursPro.add(label18);
        label18.setBounds(40, 250, 210, 30);

        label19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label19.setForeground(new java.awt.Color(102, 204, 255));
        label19.setText("Contrat :");
        ModifierParcoursPro.add(label19);
        label19.setBounds(480, 30, 210, 30);

        errorLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorLabel2.setForeground(new java.awt.Color(255, 51, 51));
        ModifierParcoursPro.add(errorLabel2);
        errorLabel2.setBounds(240, 440, 340, 40);

        getContentPane().add(ModifierParcoursPro);
        ModifierParcoursPro.setBounds(0, 0, 800, 500);

        ModifierInscriptionMaster.setBackground(new java.awt.Color(242, 242, 242));
        ModifierInscriptionMaster.setVisible(false);
        ModifierInscriptionMaster.setLayout(null);

        label20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label20.setForeground(new java.awt.Color(102, 204, 255));
        label20.setText("Universite :");
        ModifierInscriptionMaster.add(label20);
        label20.setBounds(560, 80, 210, 30);

        nouveauMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierInscriptionMaster.add(nouveauMaster);
        nouveauMaster.setBounds(70, 120, 220, 40);

        universite.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ModifierInscriptionMaster.add(universite);
        universite.setBounds(560, 120, 220, 40);

        label21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label21.setForeground(new java.awt.Color(102, 204, 255));
        label21.setText("Nouveau Master :");
        ModifierInscriptionMaster.add(label21);
        label21.setBounds(70, 70, 210, 30);

        boutonInscription.setBackground(new java.awt.Color(102, 204, 255));
        boutonInscription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boutonInscription.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        boutonInscription.setForeground(new java.awt.Color(255, 255, 255));
        boutonInscription.setLabel("Ajouter");
        boutonInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonInscriptionActionPerformed(evt);
            }
        });
        ModifierInscriptionMaster.add(boutonInscription);
        boutonInscription.setBounds(330, 260, 250, 40);

        getContentPane().add(ModifierInscriptionMaster);
        ModifierInscriptionMaster.setBounds(0, 0, 930, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCursusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCursusActionPerformed
        // TODO add your handling code here:
        cursusUniversitaire();
    }//GEN-LAST:event_buttonCursusActionPerformed

    private void buttoninfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoninfosActionPerformed
        // TODO add your handling code here:
        ajouterInformations();
    }//GEN-LAST:event_buttoninfosActionPerformed

    private void textField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField8ActionPerformed

    private void buttonparcoursProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonparcoursProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonparcoursProActionPerformed

    private void boutonInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonInscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonInscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEtudiant().setVisible(true);
            }
        });
    }
    
   
    
    private void ajouterInformations() {
        // Récupérer les données des formulaires
        
        try {
         codepermenant = Integer.parseInt(codePermenant.getText());

            String nomEtudiant = nom.getText();
            String prenomEtudiant = prenom.getText();
            String dateNaissance = naissance.getText();
            String adresse = textField8.getText();
            String telephone = tel.getText();
            String email = mail.getText();

            if (codepermenant == 0 || nomEtudiant.isEmpty() || prenomEtudiant.isEmpty() || dateNaissance.isEmpty() || adresse.isEmpty() || telephone.isEmpty() || email.isEmpty()) {
                setErrorLabel("Veuillez remplir tous les champs ou le code permenant est null .");
//                if(false){
            } else {

                try {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");

//            dateFormat.setLenient(false);
                    Date ddateNaissance = dateFormat.parse(dateNaissance);
                dateNaissance = outputFormat .format(ddateNaissance);
                
                 // Ajouter l'étudiant à la base de données
        try {
            Connection connection = connecterDB.connecterDB();
            String queryEtudiant = "INSERT INTO etudiants (codePermanent,nom, prenom, dateNaissance, adresse, telephone, email) VALUES ( ?, ?, ?, ?, ?, ?,?)";
                       preparedStatementEtudiant = connection.prepareStatement(queryEtudiant);
             preparedStatementEtudiant.setInt(1, codepermenant);
            preparedStatementEtudiant.setString(2, nomEtudiant);
            preparedStatementEtudiant.setString(3, prenomEtudiant);
            preparedStatementEtudiant.setString(4, dateNaissance);
            preparedStatementEtudiant.setString(5, adresse);
            preparedStatementEtudiant.setString(6, telephone);
            preparedStatementEtudiant.setString(7, email);
            preparedStatementEtudiant.executeUpdate();
            
    
            preparedStatementEtudiant.close();
             // Ouvrir la fenêtre Infos
             ModifierInfosEtudiant.setVisible(false);

              ModifierCursusUniversite.setVisible(true);
                                        
//            ModifierCursusUniversite.setVisible(false);
//            ModifierInfosEtudiant.setVisible(false);
//            ModifierParcoursPro.setVisible(false);
//            ModifierInscriptionMaster.setVisible(true);
        } catch (SQLException ex) {
            ex.printStackTrace();
            setErrorLabel1( "Erreur lors de l'ajout de l'étudiant");
        }

                } catch (ParseException ex) {
                    setErrorLabel1("Format de date AAAA-MM-JJ.");

                }

            }

        } catch (Exception e) {
            setErrorLabel1("Veuillez un code permenant valide.");
        }

    }
    
     public void cursusUniversitaire(){
    int anneeDebutPromotion,anneeFinPromotion , code;
        try{
         anneeDebutPromotion = Integer.parseInt(anneDebut.getText());
         anneeFinPromotion = Integer.parseInt(anneeFin.getText());
        code= codepermenant;
        if ( anneeDebutPromotion==0 || anneeFinPromotion ==0 ) {
                setErrorLabel("l'annee ne peut pas etre nul.");
           
            }
        else{
      
      
    
       
        // Connexion à la base de données
        Connection connection = connecterDB.connecterDB();
          // Ajouter la promotion à la base de données
        try {
            String queryPromotion = "INSERT INTO promotions (annee_Debut, annee_Fin,codePermanent) VALUES (?, ?,?)";
           preparedStatementPromotion = connection.prepareStatement(queryPromotion);
            preparedStatementPromotion.setInt(1, anneeDebutPromotion);
            preparedStatementPromotion.setInt(2, anneeFinPromotion); 
            preparedStatementPromotion.setInt(3, code);
                    
         int etat=   preparedStatementPromotion.executeUpdate();
            if (etat>0){
           
           // Ouvrir la fenêtre Infos
           AcceuilEtudiant infos = new AcceuilEtudiant();
                            infos.setVisible(true);
    
                             // Fermer la fenêtre courante  
                            this.dispose(); 
//            ModifierParcoursPro.setVisible(false);
//            ModifierInscriptionMaster.setVisible(false);
            }
            preparedStatementPromotion.close();
        } catch (SQLException ex) {
            setErrorLabel("lors de l'ajout.");
        }
        
        }
        }catch(Exception e){
            e.printStackTrace();
            setErrorLabel("Veuillez remplir une date valide.");
        }

}

//      private void inscriptionMaster() {
//      
//       String nomMaster = nouveauMaster.getText();
//        String etablissement = universite.getText();
//         if (nomMaster.isEmpty() || etablissement.isEmpty()){
//        setErrorLabel("Veuillez remplir tous les champs .");
//
//         } 
//         else {
//          // Connexion à la base de données
//          Connection connection = connecterDB.connecterDB();
//        try {
//            
//      
//           
//            String queryCursus = "INSERT INTO inscriptionmaster (nomMaster, etablissement,codePermanent) VALUES (?, ?,?)";
//            preparedStatementCursus = connection.prepareStatement(queryCursus);
//            preparedStatementCursus.setString(1, nomMaster);
//            preparedStatementCursus.setString(2, etablissement);
//            preparedStatementCursus.setInt(3, codepermenant);
//            preparedStatementCursus.executeUpdate();
//            preparedStatementCursus.close();
//            
//            AcceuilEtudiant acceuil =new AcceuilEtudiant();
//            acceuil.setVisible(true);
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
//
//        // Fermeture de la connexion
//        try {
//            connection.close();
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
//         }
//      }
//     private void parcoursProfessionnel() {
//     
//     int dateDebutParcours = Integer.parseInt(anneeDebutPro.getText());
//        int  dateFinParcours = Integer.parseInt(anneFinPro.getText());
//        String posteOccupee = posteOccupe.getText();
//        String typeContrat = contrat.getText();
//        String entreprisee = entreprise.getText();
//        Connection connection = connecterDB.connecterDB();
//        
//        try {
//            String queryParcours = "INSERT INTO parcoursProfessionnels (dateDebut, dateFin, posteOccupe, typeContrat, entreprise, codePermanent) VALUES (?, ?, ?, ?, ?,?)";
//            preparedStatementParcours = connection.prepareStatement(queryParcours);
//            preparedStatementParcours.setInt(1, dateDebutParcours);
//            preparedStatementParcours.setInt(2, dateFinParcours);
//            preparedStatementParcours.setString(3, posteOccupee);
//            preparedStatementParcours.setString(4, typeContrat);
//            preparedStatementParcours.setString(5, entreprisee);
//            preparedStatementParcours.setInt(6, codepermenant);
//
//
//            preparedStatementParcours.executeUpdate();
//            preparedStatementParcours.close();
//            
//            ModifierCursusUniversite.setVisible(false);
//            ModifierInfosEtudiant.setVisible(false);
//            ModifierParcoursPro.setVisible(true);
//            ModifierInscriptionMaster.setVisible(false);
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
//
//     
//     }
//     
//     
//     
     
      private void setErrorLabel(String message) {
            errorLabel.setText("Erreur : " + message);
        }
      
      private void setErrorLabel1(String message) {
            errorLabel1.setText("Erreur : " + message);
        }

    private void setErrorLabel2(String message) {
            errorLabel2.setText("Erreur : " + message);
        }
      int  codepermenant;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel ModifierCursusUniversite;
    private java.awt.Panel ModifierInfosEtudiant;
    private java.awt.Panel ModifierInscriptionMaster;
    private java.awt.Panel ModifierParcoursPro;
    private java.awt.TextField anneDebut;
    private java.awt.TextField anneFinPro;
    private java.awt.TextField anneeDebutPro;
    private java.awt.TextField anneeFin;
    private java.awt.Button boutonInscription;
    private java.awt.Button buttonCursus;
    private java.awt.Button buttoninfos;
    private java.awt.Button buttonparcoursPro;
    private java.awt.TextField codePermenant;
    private java.awt.TextField contrat;
    private java.awt.TextField entreprise;
    private java.awt.Label errorLabel;
    private java.awt.Label errorLabel1;
    private java.awt.Label errorLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField mail;
    private java.awt.TextField naissance;
    private java.awt.TextField nom;
    private java.awt.TextField nouveauMaster;
    private java.awt.TextField posteOccupe;
    private java.awt.TextField prenom;
    private java.awt.TextField tel;
    private java.awt.TextField textField8;
    private java.awt.TextField universite;
    // End of variables declaration//GEN-END:variables
}
